load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sim",
    srcs = [
        "state.go",
        "stats.go",
    ],
    importpath = "thor/com/tm/friend-simulator/internal/sim",
    visibility = ["//com/tm/friend-simulator:__subpackages__"],
)

go_test(
    name = "sim_test",
    srcs = ["state_test.go"],
    embed = [":sim"],
)
