load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = ["handler.go"],
    importpath = "thor/com/tm/event-gateway/internal/handler",
    visibility = ["//com/tm/event-gateway:__subpackages__"],
    deps = [
        "//com/tm/event-gateway/internal/event",
        "//com/tm/event-gateway/internal/producer",
    ],
)

go_test(
    name = "handler_test",
    srcs = ["handler_test.go"],
    embed = [":handler"],
    deps = ["//com/tm/event-gateway/internal/producer"],
)
