name: 'dbt_cdp_gold'
version: '1.0.0'
config-version: 2

profile: 'cdp_gold'

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_cdp_gold:
    gold:
      +materialized: table
      +on_schema_change: append_new_columns
